plugins {
    id "com.github.johnrengelman.shadow" version "8.0.0"
    id "com.modrinth.minotaur" version "2.+"
    id "com.matthewprenger.cursegradle" version "1.4.0"
}

architectury {
    platformSetupLoomIde()
    neoForge {
        platformPackage = "neoforge"
    }
}

loom {
    accessWidenerPath = project(":common").loom.accessWidenerPath
    neoForge {
    }
    runs {
        client {
            vmArg "-XstartOnFirstThread"
        }
    }
}

def jarFileName = 'sleepyhollows-neoforge'
def changelogText = rootProject.file("CHANGELOG.md").text
archivesBaseName = jarFileName


repositories {
    mavenCentral()
    maven { url "https://maven.neoforged.net/releases" }
    maven { url "https://api.modrinth.com/maven" }
    maven { url "https://maven.blamejared.com" }
    maven { url "https://maven.neoforged.net/releases/" }
}

configurations {
    common
    shadowCommon
    compileClasspath.extendsFrom common
    runtimeClasspath.extendsFrom common
    developmentNeoForge.extendsFrom common
}

dependencies {
    neoForge "net.neoforged:neoforge:${rootProject.neoforge_version}"
    modApi "dev.architectury:architectury-neoforge:${rootProject.architectury_api_version}"

    common(project(path: ":common", configuration: "namedElements")) { transitive false }
    runtimeOnly(project(path: ":common", configuration: "runtimeElements")) { transitive false }

    compileOnly(annotationProcessor("io.github.llamalad7:mixinextras-common:0.4.1"))
    implementation(include("io.github.llamalad7:mixinextras-neoforge:0.4.1"))

    modCompileOnlyApi("maven.modrinth:embeddium:0.3.31+mc1.20.1")
    modCompileOnlyApi("maven.modrinth:oculus:1.20.1-1.7.0")

    modApi "com.terraformersmc:biolith-neoforge:${rootProject.biolith_version}"
}

processResources {
    inputs.property('mod_version', rootProject.mod_version)
    filesMatching('META-INF/neoforge.mods.toml') {
        expand(mod_version: rootProject.mod_version)
    }
}

shadowJar {
    exclude "fabric.mod.json"
    exclude "architectury.common.json"

    configurations = [project.configurations.shadowCommon]
    archiveClassifier.set("dev-shadow")
}

remapJar {
    input.set shadowJar.archiveFile
    dependsOn shadowJar
    archiveClassifier.set(null)
}

jar {
    archiveClassifier.set("dev")
}

sourcesJar {
    def commonSources = project(":common").sourcesJar
    dependsOn commonSources
    from commonSources.archiveFile.map { zipTree(it) }
}

components.java {
    withVariantsFromConfiguration(project.configurations.shadowRuntimeElements) {
        skip()
    }
}

publishing {
    publications {
        mavenForge(MavenPublication) {
            artifactId = rootProject.archives_base_name + "-" + project.name
            from components.java
        }
    }
}

modrinth {
    token = System.getenv("MODRINTH_TOKEN")
    projectId = "sleepy-hollows"
    versionNumber = rootProject.mod_version
    versionName = "${rootProject.archives_base_name}-${rootProject.mod_version} [${rootProject.minecraft_version}-neoforge]"
    versionType = "release"
    changelog = rootProject.file("CHANGELOG.md").exists() ? rootProject.file("CHANGELOG.md").text : " "
    gameVersions = [rootProject.minecraft_version]
    loaders = ["neoforge"]
    uploadFile = remapJar
    additionalFiles = [tasks.sourcesJar.archiveFile]

    dependencies {
        required.project "architectury-api"
        required.project "biolith"
    }
}

curseforge {
    apiKey = System.getenv("CURSEFORGE_API_KEY")
    project {
        id = "1124163"
        releaseType = "release"
        addGameVersion rootProject.minecraft_version
        addGameVersion "NeoForge"
        mainArtifact(remapJar) {
            displayName = "SleepyHollows - ${rootProject.mod_version} - NEOFORGE - ${rootProject.minecraft_version}"
            changelog = changelogText
            changelogType = "markdown"
        }

        relations {
            requiredDependency "architectury-api"
            requiredDependency "biolith"
        }
    }
}
