plugins {
    id "com.github.johnrengelman.shadow" version "8.0.0"
    id "com.modrinth.minotaur" version "2.+"
    id "com.matthewprenger.cursegradle" version "1.4.0"
}

architectury {
    platformSetupLoomIde()
    neoForge()
}

loom {
    accessWidenerPath = project(":common").loom.accessWidenerPath

    neoForge { }
}

repositories {
    mavenCentral()
    maven { url "https://maven.neoforged.net/releases" }
    maven { url "https://api.modrinth.com/maven" }
    maven { url "https://maven.blamejared.com" }
    maven { url "https://maven.neoforged.net/releases/" }
}

configurations {
    common
    shadowCommon
    compileClasspath.extendsFrom common
    runtimeClasspath.extendsFrom common
    developmentNeoForge.extendsFrom common
    shadowBundle
}

dependencies {
    neoForge "net.neoforged:neoforge:${rootProject.neoforge_version}"
    modApi "dev.architectury:architectury-neoforge:${rootProject.architectury_api_version}"

    common(project(path: ":common", configuration: "namedElements")) { transitive false }
    runtimeOnly(project(path: ":common", configuration: "runtimeElements")) { transitive false }

    compileOnly(annotationProcessor("io.github.llamalad7:mixinextras-common:0.4.1"))
    implementation(include("io.github.llamalad7:mixinextras-neoforge:0.4.1"))

    modCompileOnlyApi("maven.modrinth:embeddium:0.3.31+mc1.20.1")
    modCompileOnlyApi("maven.modrinth:oculus:1.20.1-1.7.0")

    modApi "com.terraformersmc:biolith-neoforge:${rootProject.biolith_version}"
}

tasks.processResources {
    inputs.property("version", project.version)
    filesMatching("META-INF/mods.toml") {
        expand(version: project.version)
    }
}

tasks.shadowJar {
    configurations = [project.configurations.shadowBundle]
    archiveClassifier = "dev-shadow"
}

tasks.remapJar {
    input.set(tasks.shadowJar.archiveFile)
}

dependencies {
    shadowBundle project(path: ":common", configuration: "transformProductionNeoForge")
}
